name: iOS Example workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test bundler for fastlane and run SwiftLint
    runs-on: macos-latest
    if: contains(github.event.comment.body, '/check')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bundle install  
        run: |
          bundle install
      - name: Install mint
        run: |
          brew install mint
          mint bootstrap
          mint run swiftlint
